"use client";

import { motion } from "framer-motion";
import { Brain, ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";

interface Props {
  report: string;
}

function parseReport(raw: string) {
  const sections: { title: string; content: string }[] = [];
  const lines = raw.split("\n");
  let current: { title: string; content: string } | null = null;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current) sections.push(current);
      current = { title: line.replace("## ", "").trim(), content: "" };
    } else if (current) {
      current.content += line + "\n";
    }
  }
  if (current) sections.push(current);
  return sections;
}

export default function AIReport({ report }: Props) {
  const [expanded, setExpanded] = useState(true);
  const sections = parseReport(report);

  return (
    <div className="glass rounded-2xl border border-border p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-indigo/20 border border-indigo/30 flex items-center justify-center">
            <Brain size={14} className="text-indigo-glow" />
          </div>
          <div>
            <h2 className="font-display font-600 text-white text-sm">
              AI Intelligence Report
            </h2>
            <p className="text-muted text-[10px] font-mono">
              Generated by WalletLens AI
            </p>
          </div>
        </div>
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-muted hover:text-white transition-colors"
        >
          {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
      </div>

      {expanded && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
        >
          {sections.map((s, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.08 }}
              className="rounded-xl border border-border bg-void/50 p-4"
            >
              <h3 className="font-display font-600 text-indigo-glow text-xs uppercase tracking-wider mb-3">
                {s.title}
              </h3>
              <div className="text-slate-300 text-sm leading-relaxed font-body whitespace-pre-wrap">
                {s.content
                  .trim()
                  .split("\n")
                  .map((line, j) =>
                    line.startsWith("-") || line.startsWith("•") ? (
                      <p key={j} className="flex gap-2 mb-1">
                        <span className="text-indigo mt-1 shrink-0">▸</span>
                        <span>{line.replace(/^[-•]\s*/, "")}</span>
                      </p>
                    ) : (
                      <p key={j} className="mb-1">
                        {line}
                      </p>
                    )
                  )}
              </div>
            </motion.div>
          ))}
        </motion.div>
      )}
    </div>
  );
}